package view.dialogs.beneficiario;

import controller.BeneficiarioController;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.Beneficiario;
import utils.BeneficiarioEnum;
import view.panels.BeneficiarioPanelView;

/**
 *
 * @author manuelkalueka
 */
public class CriarBeneficiarioDialog extends javax.swing.JDialog {

  private static final BeneficiarioController controller = new BeneficiarioController();
  private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CriarBeneficiarioDialog.class.getName());

  private static BeneficiarioPanelView parentPanel;

  /**
   * Creates new form BeneficiarioDialog
   */
  public CriarBeneficiarioDialog(java.awt.Frame parent, boolean modal, BeneficiarioPanelView parentPanel) {
    super(parent, modal);
    initComponents();
    this.setLocationRelativeTo(parent);
    this.parentPanel = parentPanel;

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    txt_nome = new javax.swing.JTextField();
    txt_documento = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    txt_telefone = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    cmb_tipo = new javax.swing.JComboBox<>();
    btn_criar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));

    jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(38, 78, 202));
    jLabel1.setText("Criar Beneficiario");

    jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(0, 51, 204));
    jLabel2.setText("Nome Completo");

    txt_nome.setBackground(new java.awt.Color(255, 255, 255));
    txt_nome.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
    txt_nome.setForeground(new java.awt.Color(102, 102, 102));
    txt_nome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    txt_nome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 78, 202)));

    txt_documento.setBackground(new java.awt.Color(255, 255, 255));
    txt_documento.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
    txt_documento.setForeground(new java.awt.Color(51, 51, 51));
    txt_documento.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    txt_documento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 78, 202)));

    jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(0, 51, 255));
    jLabel3.setText("Nº de Identidade");

    jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(0, 51, 204));
    jLabel4.setText("Telefone");

    txt_telefone.setBackground(new java.awt.Color(255, 255, 255));
    txt_telefone.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
    txt_telefone.setForeground(new java.awt.Color(51, 51, 51));
    txt_telefone.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    txt_telefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 78, 202)));

    jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(0, 51, 255));
    jLabel5.setText("Tipo");

    cmb_tipo.setBackground(new java.awt.Color(255, 255, 255));
    cmb_tipo.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
    cmb_tipo.setForeground(new java.awt.Color(51, 51, 51));
    cmb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INDIVIDUAL", "FAMILIA", "COMUNIDADE" }));
    cmb_tipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 78, 202)));

    btn_criar.setBackground(new java.awt.Color(38, 78, 202));
    btn_criar.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
    btn_criar.setForeground(new java.awt.Color(255, 255, 255));
    btn_criar.setText("Criar");
    btn_criar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_criarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addGap(41, 41, 41)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel2)
          .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4)
          .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jLabel5)
          .addComponent(jLabel3)
          .addComponent(txt_documento)
          .addComponent(cmb_tipo, 0, 283, Short.MAX_VALUE))
        .addGap(53, 53, 53))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(263, 263, 263)
            .addComponent(jLabel1))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(227, 227, 227)
            .addComponent(btn_criar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(15, 15, 15)
        .addComponent(jLabel1)
        .addGap(66, 66, 66)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(txt_documento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(31, 31, 31)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(jLabel5))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(cmb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(81, 81, 81)
        .addComponent(btn_criar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(129, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btn_criarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_criarActionPerformed
    try {
      if (!camposValidados()) {
        return;
      }

      String tipoSelecionado = cmb_tipo.getSelectedItem().toString();
      BeneficiarioEnum tipo
              = BeneficiarioEnum.valueOf(tipoSelecionado);
      Beneficiario beneficiario;
      beneficiario = new Beneficiario(txt_nome.getText().trim(), tipo, txt_documento.getText().trim().toUpperCase(), txt_telefone.getText().trim(), true);

      controller.salvar(beneficiario);
      JOptionPane.showMessageDialog(null, "Beneficiario criado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

      parentPanel.listarDados();

      this.dispose();

    } catch (ClassNotFoundException | SQLException ex) {
      System.getLogger(CriarBeneficiarioDialog.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
    }
  }//GEN-LAST:event_btn_criarActionPerformed

  private boolean camposValidados() {
    if (txt_nome.getText().isEmpty()) {
      JOptionPane.showMessageDialog(
              null,
              "Campo nome é obrigatório",
              "Aviso",
              JOptionPane.WARNING_MESSAGE
      );
      return false;
    }

    if (txt_documento.getText().isEmpty()) {
      JOptionPane.showMessageDialog(
              null,
              "Campo documento é obrigatório",
              "Aviso",
              JOptionPane.WARNING_MESSAGE
      );
      return false;
    }

    String bi = txt_documento.getText().trim().toUpperCase();

    if (!bi.matches("^\\d{9}[A-Z]{2}\\d{3}$")) {
      JOptionPane.showMessageDialog(
              null,
              "Formato de BI inválido. Ex.: 020464029UE059",
              "Aviso",
              JOptionPane.WARNING_MESSAGE
      );
      return false;
    }

    if (txt_telefone.getText().isEmpty()) {
      JOptionPane.showMessageDialog(
              null,
              "Campo telefone é obrigatório",
              "Aviso",
              JOptionPane.WARNING_MESSAGE
      );
      return false;
    }

    return true;
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
      logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        CriarBeneficiarioDialog dialog = new CriarBeneficiarioDialog(new javax.swing.JFrame(), true, parentPanel);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_criar;
  private javax.swing.JComboBox<String> cmb_tipo;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JTextField txt_documento;
  private javax.swing.JTextField txt_nome;
  private javax.swing.JTextField txt_telefone;
  // End of variables declaration//GEN-END:variables
}
