package view;

import controller.BeneficiarioController;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Beneficiario;

/**
 *
 * @author manuelkalueka
 */
public class BeneficiarioPanelView extends javax.swing.JPanel {

  DefaultTableModel tabelaModelo = new DefaultTableModel(new Object[]{
    "Nome", "Tipo", "Documento", "Telefone", "Estado"}, 0);
  BeneficiarioController beneficarioController = new BeneficiarioController();

  /**
   * Creates new form BeneficiarioPanelView
   */
  public BeneficiarioPanelView() {
    initComponents();
    tb_beneficiario.setModel(tabelaModelo);
    this.setSize(760, 720);
    listarDados();
  }

  private void listarDados() {
    try {
      tabelaModelo.setRowCount(0);

      List<Beneficiario> listaBeneficiarios = beneficarioController.listar();

      for (Beneficiario b : listaBeneficiarios) {

        tabelaModelo.addRow(new Object[]{
          b.getNome(),
          b.getTipo(),
          b.getDocumento(),
          b.getTelefone(),
          b.isAtivo() ? "Sim" : "Não"
        });
      }
    } catch (ClassNotFoundException | SQLException ex) {
      System.getLogger(BeneficiarioPanelView.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tb_beneficiario = new javax.swing.JTable();
    btn_Eliminar = new javax.swing.JButton();
    btn_Novo = new javax.swing.JButton();
    btn_Editar1 = new javax.swing.JButton();

    jPanel1.setMaximumSize(new java.awt.Dimension(760, 720));
    jPanel1.setPreferredSize(new java.awt.Dimension(760, 720));

    tb_beneficiario.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane1.setViewportView(tb_beneficiario);

    btn_Eliminar.setBackground(new java.awt.Color(243, 32, 19));
    btn_Eliminar.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
    btn_Eliminar.setForeground(new java.awt.Color(255, 255, 255));
    btn_Eliminar.setText("Eliminar");

    btn_Novo.setBackground(new java.awt.Color(38, 78, 202));
    btn_Novo.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
    btn_Novo.setForeground(new java.awt.Color(255, 255, 255));
    btn_Novo.setText("Novo");

    btn_Editar1.setBackground(new java.awt.Color(255, 255, 255));
    btn_Editar1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
    btn_Editar1.setForeground(new java.awt.Color(38, 78, 202));
    btn_Editar1.setText("Editar");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(43, 43, 43)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(btn_Novo)
            .addGap(34, 34, 34)
            .addComponent(btn_Editar1)
            .addGap(34, 34, 34)
            .addComponent(btn_Eliminar))
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(113, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(41, 41, 41)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btn_Novo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_Editar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(76, 76, 76)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(178, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 844, Short.MAX_VALUE)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
          .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 584, Short.MAX_VALUE)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
          .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_Editar1;
  private javax.swing.JButton btn_Eliminar;
  private javax.swing.JButton btn_Novo;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable tb_beneficiario;
  // End of variables declaration//GEN-END:variables
}
