package view;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manuelkalueka
 */
public class DoacaoPanelView extends javax.swing.JPanel {

  DefaultTableModel tabelaModeloDoacao = new DefaultTableModel(new Object[]{
    "Descrição", "Valor", "Data de Doação", "Tipo de Bem"}, 0);

  /**
   * Creates new form DoacaoPanelView
   */
  public DoacaoPanelView() {
    initComponents();
    tb_doacao.setModel(tabelaModeloDoacao);
    this.setSize(760, 720);

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    tb_doacao = new javax.swing.JTable();
    btn_Eliminar = new javax.swing.JButton();
    btn_Novo = new javax.swing.JButton();
    btn_Editar1 = new javax.swing.JButton();

    setMaximumSize(new java.awt.Dimension(760, 720));
    setPreferredSize(new java.awt.Dimension(760, 720));

    tb_doacao.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane1.setViewportView(tb_doacao);

    btn_Eliminar.setBackground(new java.awt.Color(243, 32, 19));
    btn_Eliminar.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
    btn_Eliminar.setForeground(new java.awt.Color(255, 255, 255));
    btn_Eliminar.setText("Eliminar");

    btn_Novo.setBackground(new java.awt.Color(38, 78, 202));
    btn_Novo.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
    btn_Novo.setForeground(new java.awt.Color(255, 255, 255));
    btn_Novo.setText("Nova Doação");

    btn_Editar1.setBackground(new java.awt.Color(255, 255, 255));
    btn_Editar1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
    btn_Editar1.setForeground(new java.awt.Color(38, 78, 202));
    btn_Editar1.setText("Editar");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(32, 32, 32)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(btn_Novo)
            .addGap(34, 34, 34)
            .addComponent(btn_Editar1)
            .addGap(34, 34, 34)
            .addComponent(btn_Eliminar))
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(82, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(50, 50, 50)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btn_Novo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_Editar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(76, 76, 76)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(145, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_Editar1;
  private javax.swing.JButton btn_Eliminar;
  private javax.swing.JButton btn_Novo;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable tb_doacao;
  // End of variables declaration//GEN-END:variables
}
