package view;

import controller.UsuarioController;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.Usuario;
import utils.PasswordUtil;

/**
 *
 * @author manuelkalueka
 */
public class LoginView extends javax.swing.JFrame {

  private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginView.class.getName());
  private static final UsuarioController userController = new UsuarioController();

  /**
   * Creates new form LoginView
   */
  public LoginView() {
    initComponents();
    this.setLocationRelativeTo(this);
    this.setResizable(false);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    logo = new javax.swing.JLabel();
    txt_password = new javax.swing.JTextField();
    txt_username = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Login");
    setAlwaysOnTop(true);
    setMinimumSize(new java.awt.Dimension(940, 820));

    jPanel1.setBackground(new java.awt.Color(38, 78, 202));
    jPanel1.setForeground(new java.awt.Color(255, 255, 255));

    logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/logo_icon.png"))); // NOI18N
    logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    logo.setIconTextGap(0);
    logo.setMaximumSize(new java.awt.Dimension(20, 20));
    logo.setMinimumSize(new java.awt.Dimension(20, 20));
    logo.setPreferredSize(new java.awt.Dimension(20, 20));
    logo.setRequestFocusEnabled(false);
    logo.setSize(new java.awt.Dimension(20, 20));

    txt_password.setBackground(new java.awt.Color(38, 78, 202));
    txt_password.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
    txt_password.setForeground(new java.awt.Color(255, 255, 255));
    txt_password.setHorizontalAlignment(javax.swing.JTextField.LEFT);

    txt_username.setBackground(new java.awt.Color(38, 78, 202));
    txt_username.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
    txt_username.setForeground(new java.awt.Color(255, 255, 255));
    txt_username.setHorizontalAlignment(javax.swing.JTextField.LEFT);

    jButton1.setBackground(new java.awt.Color(255, 255, 255));
    jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
    jButton1.setForeground(new java.awt.Color(38, 78, 202));
    jButton1.setText("Entrar");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("Não tem conta?");

    jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel2.setText("Criar");
    jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        jLabel2MousePressed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addGap(399, 399, 399)
        .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        .addGap(430, 430, 430))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(286, 286, 286)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addComponent(txt_username, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
            .addComponent(txt_password)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(21, 21, 21)
        .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        .addGap(35, 35, 35)
        .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(50, 50, 50)
        .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(64, 64, 64)
        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(jLabel2))
        .addGap(327, 327, 327))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try {
        Usuario usuario = userController.buscarUsuarioPorUsername(
                txt_username.getText().trim()
        );

        if (usuario == null) {
          JOptionPane.showMessageDialog(
                  this,
                  "Credenciais inválidas",
                  "Erro",
                  JOptionPane.WARNING_MESSAGE
          );
          return;
        }

        String senhaHashInformada
                = PasswordUtil.hashPassword(txt_password.getText());

        if (!senhaHashInformada.equals(usuario.getSenha())) {
          JOptionPane.showMessageDialog(
                  this,
                  "Credenciais inválidas",
                  "Erro",
                  JOptionPane.WARNING_MESSAGE
          );
          return;
        }

        MainScreenView doacaoView = new MainScreenView();
        doacaoView.setTitle("Menu Inicial");

        doacaoView.setVisible(true);

        this.dispose();
      } catch (ClassNotFoundException | SQLException ex) {
        System.getLogger(LoginView.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
      }
    }//GEN-LAST:event_jButton1ActionPerformed

  private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
    // TODO add your handling code here:
    CadastroUsuario cadastroScreen = new CadastroUsuario();
    cadastroScreen.setVisible(true);
    this.dispose();
  }//GEN-LAST:event_jLabel2MousePressed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
      logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new LoginView().setVisible(true));
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel logo;
  private javax.swing.JTextField txt_password;
  private javax.swing.JTextField txt_username;
  // End of variables declaration//GEN-END:variables
}
