package view;

import java.awt.CardLayout;

/**
 *
 * @author manuelkalueka
 */
public class MainScreenView extends javax.swing.JFrame {

  

  private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainScreenView.class.getName());

  /**
   * Creates new form DoacaoView
   */
  public MainScreenView() {
    initComponents();
    this.setLocationRelativeTo(this);
   
    this.setResizable(false);
    setSize(940, 720);
    initCards();
  }

  private void initCards() {
    ContentPanel.setLayout(new CardLayout());

    ContentPanel.add(new DashboardPanelView(), "DASHBOARD");
    ContentPanel.add(new DoacaoPanelView(), "DOACAO");
    ContentPanel.add(new BeneficiarioPanelView(), "BENEFICIARIO");
    ContentPanel.add(new ProjetoPanelView(), "PROJETO");

    navegar("DASHBOARD");
  }

  public void navegar(String nomeTela) {
    CardLayout cl = (CardLayout) ContentPanel.getLayout();
    cl.show(ContentPanel, nomeTela);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jpanel1 = new javax.swing.JPanel();
    SidebarPanel = new javax.swing.JPanel();
    logo = new javax.swing.JLabel();
    side_projectoss = new javax.swing.JButton();
    side_dashboard = new javax.swing.JButton();
    side_beneficiario = new javax.swing.JButton();
    side_doacao = new javax.swing.JButton();
    ContentPanel = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jpanel1.setBackground(new java.awt.Color(255, 255, 255));

    SidebarPanel.setBackground(new java.awt.Color(38, 78, 202));
    SidebarPanel.setPreferredSize(new java.awt.Dimension(180, 680));

    logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/logo_icon.png"))); // NOI18N
    logo.setToolTipText("");
    logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    logo.setIconTextGap(0);
    logo.setMaximumSize(new java.awt.Dimension(20, 20));
    logo.setMinimumSize(new java.awt.Dimension(20, 20));
    logo.setPreferredSize(new java.awt.Dimension(20, 20));
    logo.setRequestFocusEnabled(false);
    logo.setSize(new java.awt.Dimension(20, 20));

    side_projectoss.setBackground(new java.awt.Color(57, 82, 159));
    side_projectoss.setForeground(new java.awt.Color(255, 255, 255));
    side_projectoss.setText("Projectos");
    side_projectoss.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    side_projectoss.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        side_projectossActionPerformed(evt);
      }
    });

    side_dashboard.setBackground(new java.awt.Color(57, 82, 159));
    side_dashboard.setForeground(new java.awt.Color(255, 255, 255));
    side_dashboard.setText("Dashboard");
    side_dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    side_dashboard.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        side_dashboardActionPerformed(evt);
      }
    });

    side_beneficiario.setBackground(new java.awt.Color(57, 82, 159));
    side_beneficiario.setForeground(new java.awt.Color(255, 255, 255));
    side_beneficiario.setText("Beneficiário");
    side_beneficiario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    side_beneficiario.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        side_beneficiarioActionPerformed(evt);
      }
    });

    side_doacao.setBackground(new java.awt.Color(57, 82, 159));
    side_doacao.setForeground(new java.awt.Color(255, 255, 255));
    side_doacao.setText("Doação");
    side_doacao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    side_doacao.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        side_doacaoActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout SidebarPanelLayout = new javax.swing.GroupLayout(SidebarPanel);
    SidebarPanel.setLayout(SidebarPanelLayout);
    SidebarPanelLayout.setHorizontalGroup(
      SidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(SidebarPanelLayout.createSequentialGroup()
        .addGap(17, 17, 17)
        .addGroup(SidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(side_doacao, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(side_beneficiario, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(side_projectoss, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(side_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(14, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidebarPanelLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(40, 40, 40))
    );
    SidebarPanelLayout.setVerticalGroup(
      SidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(SidebarPanelLayout.createSequentialGroup()
        .addGap(18, 18, 18)
        .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        .addGap(31, 31, 31)
        .addComponent(side_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(39, 39, 39)
        .addComponent(side_doacao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(33, 33, 33)
        .addComponent(side_beneficiario, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(31, 31, 31)
        .addComponent(side_projectoss, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(261, 261, 261))
    );

    ContentPanel.setBackground(new java.awt.Color(255, 255, 255));
    ContentPanel.setLayout(new java.awt.CardLayout());

    javax.swing.GroupLayout jpanel1Layout = new javax.swing.GroupLayout(jpanel1);
    jpanel1.setLayout(jpanel1Layout);
    jpanel1Layout.setHorizontalGroup(
      jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jpanel1Layout.createSequentialGroup()
        .addComponent(SidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(ContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jpanel1Layout.setVerticalGroup(
      jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(SidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
      .addComponent(ContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void side_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_side_dashboardActionPerformed
    
    navegar("DASHBOARD");
  }//GEN-LAST:event_side_dashboardActionPerformed

  private void side_doacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_side_doacaoActionPerformed
    
    navegar("DOACAO");
  }//GEN-LAST:event_side_doacaoActionPerformed

  private void side_beneficiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_side_beneficiarioActionPerformed
    
    navegar("BENEFICIARIO");
  }//GEN-LAST:event_side_beneficiarioActionPerformed

  private void side_projectossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_side_projectossActionPerformed
    
    navegar("PROJETO");
  }//GEN-LAST:event_side_projectossActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
      logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new MainScreenView().setVisible(true));
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel ContentPanel;
  private javax.swing.JPanel SidebarPanel;
  private javax.swing.JPanel jpanel1;
  private javax.swing.JLabel logo;
  private javax.swing.JButton side_beneficiario;
  private javax.swing.JButton side_dashboard;
  private javax.swing.JButton side_doacao;
  private javax.swing.JButton side_projectoss;
  // End of variables declaration//GEN-END:variables
}
