package view.panels;

import controller.ProjetoController;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Projeto;
import view.dialogs.projetos.CriarProjetoDialog;
import view.dialogs.projetos.EditarProjetoDialog;

/**
 *
 * @author manuelkalueka
 */
public class ProjetoPanelView extends javax.swing.JPanel {

  DefaultTableModel tabelaModelo = new DefaultTableModel(new Object[]{
    "Nome", "Descricao", "Data Inicio", "Data Fim", "Estado"}, 0);
  ProjetoController projetoController = new ProjetoController();
  private List<Projeto> listaProjetos = null;

  /**
   * Creates new form ProjetoPanelView
   */
  public ProjetoPanelView() {
    initComponents();
    tb_projeto.setModel(tabelaModelo);
    listarDados();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tb_projeto = new javax.swing.JTable();
    btn_Eliminar = new javax.swing.JButton();
    btn_Novo = new javax.swing.JButton();
    btn_Editar1 = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();

    setBackground(new java.awt.Color(255, 255, 255));

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.setMaximumSize(new java.awt.Dimension(760, 720));
    jPanel1.setPreferredSize(new java.awt.Dimension(760, 720));

    tb_projeto.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane1.setViewportView(tb_projeto);

    btn_Eliminar.setBackground(new java.awt.Color(243, 32, 19));
    btn_Eliminar.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
    btn_Eliminar.setForeground(new java.awt.Color(255, 255, 255));
    btn_Eliminar.setText("Eliminar");
    btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_EliminarActionPerformed(evt);
      }
    });

    btn_Novo.setBackground(new java.awt.Color(38, 78, 202));
    btn_Novo.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
    btn_Novo.setForeground(new java.awt.Color(255, 255, 255));
    btn_Novo.setText("Novo");
    btn_Novo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_NovoActionPerformed(evt);
      }
    });

    btn_Editar1.setBackground(new java.awt.Color(255, 255, 255));
    btn_Editar1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
    btn_Editar1.setForeground(new java.awt.Color(38, 78, 202));
    btn_Editar1.setText("Editar");
    btn_Editar1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_Editar1ActionPerformed(evt);
      }
    });

    jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(38, 78, 202));
    jLabel1.setText("Projetos");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(43, 43, 43)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_Novo)
            .addGap(34, 34, 34)
            .addComponent(btn_Editar1)
            .addGap(34, 34, 34)
            .addComponent(btn_Eliminar))
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(113, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(41, 41, 41)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btn_Novo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_Editar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel1))
        .addGap(76, 76, 76)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(175, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed

    int linhaSelecionada = tb_projeto.getSelectedRow();
    if (linhaSelecionada == -1) {
      JOptionPane.showMessageDialog(null, "Selecione uma linha para apagar!", "Aviso", JOptionPane.WARNING_MESSAGE);
      return;
    }
    int answer = JOptionPane.showConfirmDialog(null, "Tens certeza?", "Aviso", JOptionPane.WARNING_MESSAGE);
    if (answer == 0) {
      try {
        Projeto projEncontrado = listaProjetos.get(linhaSelecionada);
        projetoController.excluir(projEncontrado.getId_projeto());

        listarDados();
      } catch (ClassNotFoundException | SQLException ex) {
        System.getLogger(ProjetoPanelView.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
      } finally {
        tb_projeto.clearSelection();
      }
    }
  }//GEN-LAST:event_btn_EliminarActionPerformed

  private void btn_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NovoActionPerformed
    java.awt.Frame parent = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
    CriarProjetoDialog dialog = new CriarProjetoDialog(parent, true, this);

    dialog.setVisible(true);
  }//GEN-LAST:event_btn_NovoActionPerformed

  private void btn_Editar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Editar1ActionPerformed

    int linhaSelecionada = tb_projeto.getSelectedRow();
    if (linhaSelecionada == -1) {
      JOptionPane.showMessageDialog(null, "Selecione uma linha para Editar!", "Aviso", JOptionPane.WARNING_MESSAGE);
      return;
    }

    java.awt.Frame parent = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
    EditarProjetoDialog dialog = new EditarProjetoDialog(parent, true, this);

    Projeto projParaEditar = listaProjetos.get(linhaSelecionada);

    dialog.setProtejoForEdicao(projParaEditar);
    dialog.setVisible(true);
  }//GEN-LAST:event_btn_Editar1ActionPerformed

  public void listarDados() {

    tabelaModelo.setRowCount(0);
    try {
      this.listaProjetos = projetoController.listar();
    } catch (ClassNotFoundException ex) {
      System.getLogger(ProjetoPanelView.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
    } catch (SQLException ex) {
      System.getLogger(ProjetoPanelView.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
    }
    for (Projeto p : listaProjetos) {

      tabelaModelo.addRow(new Object[]{
        p.getNome(),
        p.getDescricao(),
        p.getData_criacao().toString(),
        p.getData_fim() != null ? p.getData_fim().toString() : "em andamento",
        p.getStatus()
      });
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_Editar1;
  private javax.swing.JButton btn_Eliminar;
  private javax.swing.JButton btn_Novo;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable tb_projeto;
  // End of variables declaration//GEN-END:variables
}
