package view.dialogs.projetos;

import controller.ProjetoController;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import model.Projeto;
import utils.CustomezedEnum;
import view.panels.ProjetoPanelView;

/**
 *
 * @author manuelkalueka
 */
public class CriarProjetoDialog extends javax.swing.JDialog {

  private static final ProjetoController controller = new ProjetoController();
  private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CriarProjetoDialog.class.getName());
  private static final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

  private static ProjetoPanelView parentPanel;

  /**
   * Creates new form BeneficiarioDialog
   */
  public CriarProjetoDialog(java.awt.Frame parent, boolean modal, ProjetoPanelView parentPanel) {
    super(parent, modal);
    initComponents();
    this.setLocationRelativeTo(parent);
    this.parentPanel = parentPanel;

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    txt_nome = new javax.swing.JTextField();
    txt_descricao = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    btn_criar = new javax.swing.JButton();
    txt_data_fim = new javax.swing.JFormattedTextField();
    txt_data_inicio = new javax.swing.JFormattedTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));

    jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(38, 78, 202));
    jLabel1.setText("Criar Projecto");

    jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(0, 51, 204));
    jLabel2.setText("Nome");

    txt_nome.setBackground(new java.awt.Color(255, 255, 255));
    txt_nome.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
    txt_nome.setForeground(new java.awt.Color(102, 102, 102));
    txt_nome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    txt_nome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 78, 202)));

    txt_descricao.setBackground(new java.awt.Color(255, 255, 255));
    txt_descricao.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
    txt_descricao.setForeground(new java.awt.Color(51, 51, 51));
    txt_descricao.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    txt_descricao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 78, 202)));

    jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(0, 51, 255));
    jLabel3.setText("Descrição");

    jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(0, 51, 204));
    jLabel4.setText("Data Inicio");

    jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(0, 51, 255));
    jLabel5.setText("Data Fim");

    btn_criar.setBackground(new java.awt.Color(38, 78, 202));
    btn_criar.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
    btn_criar.setForeground(new java.awt.Color(255, 255, 255));
    btn_criar.setText("Criar");
    btn_criar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_criarActionPerformed(evt);
      }
    });

    txt_data_fim.setBackground(new java.awt.Color(255, 255, 255));
    txt_data_fim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 78, 202)));
    txt_data_fim.setForeground(new java.awt.Color(51, 51, 51));
    txt_data_fim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
    txt_data_fim.setHorizontalAlignment(javax.swing.JTextField.LEFT);

    txt_data_inicio.setBackground(new java.awt.Color(255, 255, 255));
    txt_data_inicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 78, 202)));
    txt_data_inicio.setForeground(new java.awt.Color(51, 51, 51));
    txt_data_inicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
    txt_data_inicio.setHorizontalAlignment(javax.swing.JTextField.LEFT);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addGap(41, 41, 41)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel2)
          .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4)
          .addComponent(txt_data_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(txt_data_fim, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel5)
          .addComponent(jLabel3)
          .addComponent(txt_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(53, 53, 53))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btn_criar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(304, 304, 304))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(316, 316, 316)
        .addComponent(jLabel1)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(17, 17, 17)
        .addComponent(jLabel1)
        .addGap(64, 64, 64)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(txt_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(31, 31, 31)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(jLabel5))
        .addGap(22, 22, 22)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txt_data_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txt_data_fim, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(82, 82, 82)
        .addComponent(btn_criar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(115, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btn_criarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_criarActionPerformed
    try {
      if (!camposValidados()) {
        return;
      }

      LocalDate dataInicio;
      try {
        dataInicio = LocalDate.parse(txt_data_inicio.getText().trim(), formatter);
      } catch (DateTimeParseException e) {
        JOptionPane.showMessageDialog(this,
                "Informe uma data de início válida (dd/MM/yyyy)",
                "Validação",
                JOptionPane.WARNING_MESSAGE);
        return;
      }

      LocalDate dataFim = null;
      String textoDataFim = txt_data_fim.getText().trim();

      if (!textoDataFim.isEmpty() && !textoDataFim.contains(" ")) {
        try {
          dataFim = LocalDate.parse(textoDataFim, formatter);
        } catch (DateTimeParseException e) {
          JOptionPane.showMessageDialog(this,
                  "Data de fim inválida (dd/MM/yyyy)",
                  "Validação",
                  JOptionPane.WARNING_MESSAGE);
          return;
        }
      }
      Projeto projeto = new Projeto(
              txt_nome.getText().trim(),
              txt_descricao.getText().trim(),
              dataInicio);

      projeto.setData_fim(dataFim);
      projeto.setStatus(CustomezedEnum.ATIVO);

      controller.salvar(projeto);

      JOptionPane.showMessageDialog(null, "projeto criado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

      parentPanel.listarDados();

      this.dispose();

    } catch (ClassNotFoundException | SQLException ex) {
      System.getLogger(CriarProjetoDialog.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
    }
  }//GEN-LAST:event_btn_criarActionPerformed

  private boolean camposValidados() {
    if (txt_nome.getText().isEmpty()) {
      JOptionPane.showMessageDialog(
              null,
              "Campo nome é obrigatório",
              "Aviso",
              JOptionPane.WARNING_MESSAGE
      );
      return false;
    }

    if (txt_descricao.getText().isEmpty()) {
      JOptionPane.showMessageDialog(
              null,
              "Campo Descricao é obrigatório",
              "Aviso",
              JOptionPane.WARNING_MESSAGE
      );
      return false;
    }

    if (txt_data_inicio.getText().isEmpty()) {
      JOptionPane.showMessageDialog(
              null,
              "Campo Data é obrigatório",
              "Aviso",
              JOptionPane.WARNING_MESSAGE
      );
      return false;
    }

    return true;
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
      logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        CriarProjetoDialog dialog = new CriarProjetoDialog(new javax.swing.JFrame(), true, parentPanel);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_criar;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JFormattedTextField txt_data_fim;
  private javax.swing.JFormattedTextField txt_data_inicio;
  private javax.swing.JTextField txt_descricao;
  private javax.swing.JTextField txt_nome;
  // End of variables declaration//GEN-END:variables
}
